### ISSUE TITLE
Installation may cause R# to stall while "Processing Source Files"

### ISSUE THREAD

**Issue by rjmurillo** [ERNICommunity/AgentMulder#13]
Love the plugin, but had to uninstall because of this issue.

It is mentioned in the JetBrains issue tracker as well: https://youtrack.jetbrains.com/issue/RSRP-465100

**Comment by mareklinka** [comment]
Yes, we are aware and I think we have a fix for this implemented, but we are waiting for JetBrains to drop R# 2017.2 to go live with it. We might reconsider and deploy it sooner. I'll update the issue when I know more.

**Comment by mareklinka** [comment]
Sorry for the delay, it's difficult to schedule releases during the vacation period. At any rate, Mulder for R# 2017.2 has been released last week and should contain the fix for this issue. There is also a set of improvements waiting to be deployed as 2017.2.1 that should make DI detection more robust.

I'm closing this issue - if you manage to test it and still have problems, go ahead and reopen.
