### ISSUE TITLE
Resharper 2019 support

### ISSUE THREAD

**Issue by Advitalitum** [ERNICommunity/AgentMulder#40]

**Comment by matkoch** [comment]
@mareklinka do you need help with the update?

**Comment by mareklinka** [comment]
@matkoch Thanks for offering! For now I think we're fine I just haven't had time to look into the topic. But I'll try to get the update rolling as soon as possible. If I find any difficulties, I will get back to you.

**Comment by matkoch** [comment]
@mareklinka 	as far as I can see it's still not published?

**Comment by mareklinka** [comment]
Unfortunately not. Our Gallery account got destroyed, somehow:

`The account 'esk-community' from Resharper Gallery was not linked to hub account, that's why during migration ReSharper plugins to plugins repository this account was lost.`

Starting today, we have a new account and I will try to get the extension out by the end of the week, as time allows.

**Comment by matkoch** [comment]
We can also manually link the old to the new one, if you want. This way you could also keep the original plugin id.

**Comment by mareklinka** [comment]
That would be awesome, @matkoch. Do you need anything from us, apart from the new account (called `ESK Community`)?

**Comment by matkoch** [comment]
should be fixed now

**Comment by mareklinka** [comment]
Thanks a lot! I just pushed Mulder 2019.1 to the JetBrains repository. It should be showing up for download shortly.
